name: Check
on: 
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      
      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
        
      - name: Check
        run: "deno task check"
